# Generated by Django 4.0.5 on 2022-07-29 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='birds',
            new_name='with_birds',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='cats',
            new_name='with_cats',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='dogs',
            new_name='with_dogs',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='fish',
            new_name='with_fish',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='other',
            new_name='with_other',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='rabbits',
            new_name='with_rabbits',
        ),
    ]
