# Generated by Django 4.0.5 on 2022-07-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_user_bio_alter_user_hour_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('photo_url', models.URLField(blank=True, max_length=250, null=True)),
                ('bio', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_pet_owner',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
