# Generated by Django 4.0.4 on 2022-06-02 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='url',
            new_name='image_url',
        ),
    ]
